apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: k8s-cluster
  region:  ap-northeast-2
vpc:
  subnets:
    private:  # 워커노드가 속할 서브넷 : private zone 기재
      ap-northeast-2a: { id: subnet-03fa85b3cd79017e6 }   
      ap-northeast-2c: { id: subnet-0d1f750d626ab7061 }

managedNodeGroups:
  - name: k8s-3tier-node1
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
    subnets:
      - subnet-03fa85b3cd79017e6
  - name: k8s-3tier-node2
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
    subnets:
      - subnet-0d1f750d626ab7061
    iam:
      withAddonPolicies:
        imageBuilder: true